#! /bin/bash

PIDFILE=/var/run/reversessh.pid

run_hook() {
	route add default gw 192.168.178.1 eth0
	sleep 5
	dbclient -N -i .ssh/id_db-rsa_charon_tunnel -R 10.8.0.1:1234:127.0.0.1:22 janus@159.69.48.34&
	echo $! > "${PIDFILE}"
}

run_cleanuphook() {
	if [ -f "${PIDFILE}" ]; then
		kill $(cat "${PIDFILE}")
	fi
}
