#! /bin/bash

build() {
	add_binary dbclient
	mkdir -p "${BUILDROOT}"/.ssh
	cat "${KNOWN_HOSTS_FILE}" >> "${BUILDROOT}"/.ssh/known_hosts
	cat ${SSH_KEY} > "${BUILDROOT}"/.ssh/$(basename ${SSH_KEY})
	cat ${SSH_KEY}.pub > "${BUILDROOT}"/.ssh/$(basename ${SSH_KEY}).pub
	add_runscript
}
