#! /bin/bash
#
# Copyright 2020 by Karsten Lehmann <mail@kalehmann.de>
#
# This file configures the build process for the remote unlock hookst.
#
#    This file is part of the arch-remote-unlock-hooks.
#
#    The arch-remote-unlock-hooks are free software: you can redistribute them
#    and/or modify them under the terms of the GNU General Public License as
#    published by the Free Software Foundation, either version 3 of the License,
#    or (at your option) any later version.
#
#    The arch-remote-unlock-hooks are are distributed in the hope that they will
#    be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with the arch-remote-unlock-hooks.  If not, see
#    <https://www.gnu.org/licenses/>.

build() {
	add_binary dbclient
	mkdir -p "${BUILDROOT}"/root/.ssh
	cat "${KNOWN_HOSTS_FILE}" >> "${BUILDROOT}"/root/.ssh/known_hosts
	cat ${SSH_KEY} > "${BUILDROOT}"/root/.ssh/$(basename ${SSH_KEY})
	cat ${SSH_KEY}.pub > "${BUILDROOT}"/root/.ssh/$(basename ${SSH_KEY}).pub
	add_runscript
}
