#! /bin/bash
#
# Copyright 2020 by Karsten Lehmann <mail@kalehmann.de>
#
# This file configures the build process for the remote unlock hookst.
#
#    This file is part of the arch-remote-unlock-hooks.
#
#    The arch-remote-unlock-hooks are free software: you can redistribute them
#    and/or modify them under the terms of the GNU General Public License as
#    published by the Free Software Foundation, either version 3 of the License,
#    or (at your option) any later version.
#
#    The arch-remote-unlock-hooks are are distributed in the hope that they will
#    be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with the arch-remote-unlock-hooks.  If not, see
#    <https://www.gnu.org/licenses/>.

build() {
        # Configure the prompt for the root user to display the user name in
        # green '@' the 'initramfs' and set an 'll' as an alias to 'ls -l'.
	cat <<'EOF' > "${BUILDROOT}"/root/.profile
NC='\033[0m'
RED='\033[0;31m'
GREEN='\033[0;32m'
PS1="\${GREEN}\u\${NC}@\${RED}initramfs\${NC}:\${GREEN}\W ${NC}# "
alias ll='ls -l'
EOF
        # Create the a new shell for the root user, that utilizes the previous
        # creates provile and gives the user a short description how to unlock
        # the disk.
	cat <<'EOF' > "${BUILDROOT}"/bin/sshshell
#! /bin/sh
NC='\033[0m'
RED='\033[0;31m'

printf "${RED}"

echo 'Welcome to the initramfs'
echo 'You may want to run `cryptsetup_shell` to unlock the disk'
echo 'Type `exit` to resume the boot process'

printf "\n${NC}"

ENV=/root/.profile sh
EOF
	chmod +x "${BUILDROOT}"/bin/sshshell
        # Set the new shell as default for the root user.
        echo 'root:x:0:0:root:/root:/bin/sshshell' > "${BUILDROOT}"/etc/passwd
	echo '/bin/sshshell' > "${BUILDROOT}"/etc/shells
}
