#! /bin/bash

build() {
	echo 'root:x:0:0:root:/root:/bin/sshshell' > "${BUILDROOT}"/etc/passwd
	echo '/bin/sshshell' > "${BUILDROOT}"/etc/shells
	cat <<'EOF' > "${BUILDROOT}"/root/.profile
NC='\033[0m'
RED='\033[0;31m'
GREEN='\033[0;32m'
PS1="\${GREEN}\u\${NC}@\${RED}initramfs\${NC}:\${GREEN}\W ${NC}# "
alias ll='ls -l'
EOF
	cat <<'EOF' > "${BUILDROOT}"/bin/sshshell
#! /bin/sh
NC='\033[0m'
RED='\033[0;31m'

printf "${RED}"

echo 'Welcome to the initramfs'
echo 'You may want to run `cryptsetup_shell` to unlock the disk'
echo 'Type `exit` to resume the boot process'

printf "\n${NC}"

ENV=/root/.profile sh
EOF
	chmod +x "${BUILDROOT}"/bin/sshshell
}
