#! /bin/bash

build() {
	add_binary  dbclient
	mkdir -p "${BUILDROOT}"/.ssh
	cat /root/.ssh/known_hosts >> "${BUILDROOT}"/.ssh/known_hosts
	cat /root/.ssh/id_db-rsa_charon_tunnel > "${BUILDROOT}"/.ssh/id_db-rsa_charon_tunnel
	cat /root/.ssh/id_db-rsa_charon_tunnel.pub > "${BUILDROOT}"/.ssh/id_db-rsa_charon_tunnel.pub
	add_runscript
}
